# Generated by Django 5.2.7 on 2025-10-11 21:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doktor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_soyad', models.CharField(max_length=100, verbose_name='Adı Soyadı')),
                ('kidem', models.CharField(choices=[('ACEMI', 'Acemi'), ('ORTA_KIDEMLI', 'Orta Kıdemli'), ('KIDEMLI', 'Kıdemli')], max_length=20, verbose_name='Kıdem')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı Hesabı')),
            ],
            options={
                'verbose_name': 'Doktor',
                'verbose_name_plural': 'Doktorlar',
            },
        ),
        migrations.CreateModel(
            name='IzinTalebi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarih', models.DateField(verbose_name='İzin İstenen Tarih')),
                ('doktor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='izin_talepleri', to='core.doktor')),
            ],
            options={
                'verbose_name': 'İzin Talebi',
                'verbose_name_plural': 'İzin Talepleri',
                'unique_together': {('doktor', 'tarih')},
            },
        ),
        migrations.CreateModel(
            name='Nobet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarih', models.DateField(verbose_name='Nöbet Tarihi')),
                ('bolum', models.CharField(choices=[('YESIL', 'Yeşil Alan'), ('SARI', 'Sarı Alan'), ('KIRMIZI', 'Kırmızı Alan'), ('YEDEK', 'Yedek/Diğer')], max_length=20, verbose_name='Atandığı Bölüm')),
                ('doktor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nobetleri', to='core.doktor')),
            ],
            options={
                'verbose_name': 'Nöbet',
                'verbose_name_plural': 'Nöbet Takvimi',
                'unique_together': {('doktor', 'tarih')},
            },
        ),
    ]
