# Generated by Django 5.2.7 on 2025-10-12 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HastaneAyarlari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gunluk_doktor_sayisi', models.PositiveIntegerField(default=4, verbose_name='Günlük Nöbetçi Doktor Sayısı')),
                ('minimum_dinlenme_gunu', models.PositiveIntegerField(default=2, verbose_name='İki Nöbet Arası Minimum Dinlenme Günü')),
                ('aylik_izin_limiti', models.PositiveIntegerField(default=4, verbose_name='Aylık Maksimum İzin Günü Limiti')),
            ],
            options={
                'verbose_name': 'Hastane Ayarları',
                'verbose_name_plural': 'Hastane Ayarları',
            },
        ),
    ]
