# Generated by Django 5.2.7 on 2025-10-12 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_hastaneayarlari'),
    ]

    operations = [
        migrations.AddField(
            model_name='nobet',
            name='izin_iptal_edildi',
            field=models.BooleanField(default=False, verbose_name='İzin İptal Edilerek Mi Atandı?'),
        ),
    ]
