# Generated by Django 5.2.7 on 2025-10-17 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_nobet_izin_iptal_edildi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hastaneayarlari',
            name='gunluk_doktor_sayisi',
        ),
        migrations.AddField(
            model_name='hastaneayarlari',
            name='kirmizi_alan_doktor_sayisi',
            field=models.PositiveIntegerField(default=1, verbose_name='Kırmızı Alan Doktor Sayısı'),
        ),
        migrations.AddField(
            model_name='hastaneayarlari',
            name='sari_alan_doktor_sayisi',
            field=models.PositiveIntegerField(default=1, verbose_name='Sarı Alan Doktor Sayısı'),
        ),
        migrations.AddField(
            model_name='hastaneayarlari',
            name='yesil_alan_doktor_sayisi',
            field=models.PositiveIntegerField(default=2, verbose_name='Yeşil Alan Doktor Sayısı'),
        ),
    ]
