# Generated by Django 5.2.7 on 2026-03-27 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_resmitatil'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ResmiTatil',
        ),
    ]
