# Generated by Django 5.2.7 on 2026-03-11 10:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Poliklinik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=100, verbose_name='Poliklinik Adı')),
            ],
        ),
        migrations.CreateModel(
            name='Doktor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefon', models.CharField(blank=True, max_length=15, null=True)),
                ('kullanici', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hastane_doktor_profili', to=settings.AUTH_USER_MODEL)),
                ('poliklinik', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hastane.poliklinik', verbose_name='Bölümü')),
            ],
        ),
        migrations.CreateModel(
            name='Nobet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarih', models.DateField(verbose_name='Nöbet Tarihi')),
                ('baslangic_saati', models.TimeField(default='08:00')),
                ('bitis_saati', models.TimeField(default='08:00')),
                ('doktor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nobetler', to='hastane.doktor')),
            ],
        ),
        migrations.CreateModel(
            name='NobetTakas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('durum', models.CharField(choices=[('beklemede', 'Beklemede'), ('onaylandi', 'Onaylandı'), ('reddedildi', 'Reddedildi'), ('iptal', 'İptal Edildi')], default='beklemede', max_length=15)),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('aciklama', models.TextField(blank=True, help_text='Takas için mazeret veya not', null=True)),
                ('alinacak_nobet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='karsilik_istenen_nobet', to='hastane.nobet')),
                ('hedef_doktor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bana_gelen_talepler', to='hastane.doktor')),
                ('talep_eden_doktor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yaptigim_talepler', to='hastane.doktor')),
                ('verilecek_nobet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='takasa_cikan_nobet', to='hastane.nobet')),
            ],
        ),
    ]
