# Generated by Django 5.2.7 on 2026-03-11 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hastane', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doktor',
            options={'verbose_name': 'Doktor', 'verbose_name_plural': 'Doktorlar'},
        ),
        migrations.AlterModelOptions(
            name='nobet',
            options={'verbose_name': 'Nöbet', 'verbose_name_plural': 'Nöbetler'},
        ),
        migrations.AlterModelOptions(
            name='nobettakas',
            options={'verbose_name': 'Nöbet Takas Talebi', 'verbose_name_plural': 'Nöbet Takas Talepleri'},
        ),
        migrations.AlterModelOptions(
            name='poliklinik',
            options={'verbose_name': 'Poliklinik', 'verbose_name_plural': 'Poliklinikler'},
        ),
        migrations.AddField(
            model_name='doktor',
            name='kidem',
            field=models.CharField(choices=[('ACEMI', 'Acemi'), ('ORTA_KIDEMLI', 'Orta Kıdemli'), ('KIDEMLI', 'Kıdemli')], default='ACEMI', max_length=20, verbose_name='Kıdem'),
        ),
        migrations.AddField(
            model_name='nobet',
            name='bolum',
            field=models.CharField(choices=[('YESIL', 'Yeşil Alan'), ('SARI', 'Sarı Alan'), ('KIRMIZI', 'Kırmızı Alan'), ('YEDEK', 'Yedek/Diğer')], default='YESIL', max_length=20, verbose_name='Atandığı Bölüm'),
        ),
    ]
