# Generated by Django 5.2.7 on 2026-03-11 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hastane', '0002_alter_doktor_options_alter_nobet_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IzinTalebi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarih', models.DateField(verbose_name='İzin İstenen Tarih')),
                ('doktor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='izin_talepleri', to='hastane.doktor')),
            ],
            options={
                'verbose_name': 'İzin Talebi',
                'verbose_name_plural': 'İzin Talepleri',
                'unique_together': {('doktor', 'tarih')},
            },
        ),
    ]
