# Generated by Django 5.2.7 on 2026-03-11 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hastane', '0003_izintalebi'),
    ]

    operations = [
        migrations.AddField(
            model_name='izintalebi',
            name='durum',
            field=models.CharField(choices=[('beklemede', 'Beklemede (Onay Bekliyor)'), ('onaylandi', 'Onaylandı'), ('reddedildi', 'Reddedildi')], default='beklemede', max_length=20, verbose_name='Durum'),
        ),
    ]
