# Generated by Django 5.2.7 on 2026-03-27 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hastane', '0004_izintalebi_durum'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResmiTatil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=100, verbose_name='Tatil Adı (Örn: Ramazan Bayramı 1. Gün)')),
                ('tarih', models.DateField(unique=True, verbose_name='Tatil Tarihi')),
            ],
            options={
                'verbose_name': 'Resmi Tatil',
                'verbose_name_plural': 'Resmi Tatiller',
                'ordering': ['tarih'],
            },
        ),
    ]
