# Generated by Django 5.2.7 on 2026-03-27 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hastane', '0005_resmitatil'),
    ]

    operations = [
        migrations.CreateModel(
            name='NobetHavuzu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aciklama', models.TextField(blank=True, null=True, verbose_name='Neden Devrediyor?')),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('durum', models.CharField(choices=[('aktif', 'Havuza Açık (Bekliyor)'), ('alindi', 'Biri Tarafından Alındı')], default='aktif', max_length=10)),
                ('nobet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hastane.nobet', verbose_name='Havuzdaki Nöbet')),
                ('olusturan_doktor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hastane.doktor', verbose_name='İlana Koyan Doktor')),
            ],
            options={
                'verbose_name': 'Havuz İlanı',
                'verbose_name_plural': 'Nöbet Havuzu İlanları',
                'ordering': ['-olusturulma_tarihi'],
            },
        ),
    ]
