# Generated by Django 5.2.7 on 2026-03-27 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hastane', '0006_nobethavuzu'),
    ]

    operations = [
        migrations.CreateModel(
            name='NobetTercihi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarih', models.DateField(verbose_name='İstenmeyen Nöbet Tarihi')),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('doktor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hastane.doktor', verbose_name='Doktor')),
            ],
            options={
                'verbose_name': 'Nöbet Tercihi (İstenmeyen Gün)',
                'verbose_name_plural': 'Nöbet Tercihleri',
                'ordering': ['-tarih'],
                'unique_together': {('doktor', 'tarih')},
            },
        ),
    ]
