# Generated by Django 5.2.7 on 2026-03-28 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hastane', '0007_nobettercihi'),
    ]

    operations = [
        migrations.AddField(
            model_name='doktor',
            name='telegram_chat_id',
            field=models.CharField(blank=True, help_text='Telegram bildirimleri için doktorun Chat ID numarası', max_length=50, null=True),
        ),
    ]
