# Generated by Django 5.2.7 on 2026-03-29 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hastane', '0008_doktor_telegram_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='doktor',
            name='kalan_izin_hakki',
            field=models.IntegerField(default=20, help_text='Doktorun bu yıl kullanabileceği toplam izin günü sayısı', verbose_name='Kalan İzin Hakkı (Gün)'),
        ),
    ]
