# Generated by Django 5.2.7 on 2026-03-29 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hastane', '0009_doktor_kalan_izin_hakki'),
    ]

    operations = [
        migrations.CreateModel(
            name='Duyuru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=150, verbose_name='Duyuru Başlığı')),
                ('mesaj', models.TextField(verbose_name='Duyuru İçeriği')),
                ('oncelik', models.CharField(choices=[('info', 'ℹ️ Bilgi (Mavi)'), ('warning', '⚠️ Uyarı (Sarı)'), ('danger', '🚨 Acil / Önemli (Kırmızı)')], default='info', max_length=20, verbose_name='Önem Derecesi')),
                ('tarih', models.DateTimeField(auto_now_add=True, verbose_name='Yayınlanma Tarihi')),
                ('aktif_mi', models.BooleanField(default=True, verbose_name='Yayında mı?')),
            ],
            options={
                'verbose_name': 'Başhekimlik Duyurusu',
                'verbose_name_plural': 'Başhekimlik Duyuruları',
                'ordering': ['-tarih'],
            },
        ),
        migrations.CreateModel(
            name='Bildirim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mesaj', models.CharField(max_length=255)),
                ('okundu_mu', models.BooleanField(default=False)),
                ('tarih', models.DateTimeField(auto_now_add=True)),
                ('doktor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bildirimler', to='hastane.doktor')),
            ],
            options={
                'verbose_name': 'Bildirim',
                'verbose_name_plural': 'Bildirimler',
                'ordering': ['-tarih'],
            },
        ),
    ]
