# Generated by Django 5.2.7 on 2026-03-29 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hastane', '0010_duyuru_bildirim'),
    ]

    operations = [
        migrations.AddField(
            model_name='doktor',
            name='kirmizi_alan_yetkisi',
            field=models.BooleanField(default=False, verbose_name='Kırmızı Alan Yetkisi (Kıdemli/Uzman)'),
        ),
        migrations.AddField(
            model_name='resmitatil',
            name='carpan_etkisi',
            field=models.BooleanField(default=True, verbose_name='Maaş/Puan Çarpanı Uygulansın mı?'),
        ),
    ]
