# Generated by Django 5.2.7 on 2026-03-29 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hastane', '0011_doktor_kirmizi_alan_yetkisi_resmitatil_carpan_etkisi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doktor',
            name='kirmizi_alan_yetkisi',
        ),
    ]
